name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/oohiyorioo/gmod-ptero:latest
          docker push ghcr.io/oohiyorioo/gmod-ptero:latest
